language: perl
perl:
    - "5.20"
sudo:
  false
addons:
  apt:
    packages:
    - python
    - build-essential
    - wget
    - bwa
    - bowtie
    - bowtie2
    - ncbi-blast+
    - python-cutadapt
    - emboss 
    - openjdk-8-jre-headless
    - git
    - zlib1g-dev
    - libncurses5-dev
    - libbz2-dev
    - liblzma-dev 
before_install:
    - export PATH=$TRAVIS_BUILD_DIR:/tmp/samtools-1.4.1/:/tmp/bedtools2/bin/:$PATH
    - git clone git://github.com/haarg/perl-travis-helper
    - source perl-travis-helper/init
    - build-perl
    - perl -V
install:
    - cpanm Graph Log::Log4perl IPC::Run3 Devel::Cover Devel::Cover::Report::Coveralls
    - wget -O /tmp/samtools-1.4.1.tar.bz2 https://github.com/samtools/samtools/releases/download/1.4.1/samtools-1.4.1.tar.bz2 && cd /tmp && tar xjf samtools-1.4.1.tar.bz2 && cd samtools-1.4.1 && ./configure && make && cd ..
    - wget -O /tmp/bedtools.tar.gz https://github.com/arq5x/bedtools2/releases/download/v2.27.1/bedtools-2.27.1.tar.gz && cd /tmp && tar xzf bedtools.tar.gz && cd bedtools2 && make
    - cd $TRAVIS_BUILD_DIR
    - export PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine
script:
    - travis_wait 60 true
after_success:
    - export PERL5OPT=""
    - cover -ignore_re=lib
    - cover -ignore_re=lib -report coveralls
