language: perl
perl:
    - "5.20"
sudo:
  false
addons:
  apt:
    packages:
    - python
    - build-essential
    - wget
    - bwa
    - bowtie
    - bowtie2
    - ncbi-blast+
    - emboss 
    - oracle-java8-installer
    - git
    - zlib1g-dev
    - libncurses5-dev
    - libbz2-dev
    - liblzma-dev 
    - libgsl0-dev
    - python-pip
    - libwww-perl
    - liblog-log4perl-perl
    - libipc-run-perl
    - libipc-run3-perl
    - libdevel-cover-perl
    - tree
before_install:
    - export PATH=$TRAVIS_BUILD_DIR:/tmp/gffread/gffread:/tmp/miRanda-3.3a/src:/tmp/gmap-2018-02-12/src:$HOME/.local/bin:/tmp/mirdeep2/bin:/tmp/samtools-1.4.1/:/tmp/bedtools2/bin/:/tmp/proteinortho_v5.16b/:/tmp/xa2multi/:/tmp/piranha-1.2.1/src/progs/:$PATH
    - git clone git://github.com/haarg/perl-travis-helper
    - source perl-travis-helper/init
    - build-perl
    - perl -V
install:
    - cpanm Devel::Cover Devel::Cover::Report::Coveralls RNA::HairpinFigure

    - wget -O /tmp/samtools-1.4.1.tar.bz2 https://github.com/samtools/samtools/releases/download/1.4.1/samtools-1.4.1.tar.bz2 && cd /tmp && tar xjf samtools-1.4.1.tar.bz2 && cd samtools-1.4.1 && ./configure && make && cd ..
    - wget -O /tmp/bedtools.tar.gz https://github.com/arq5x/bedtools2/releases/download/v2.27.1/bedtools-2.27.1.tar.gz && cd /tmp && tar xzf bedtools.tar.gz && cd bedtools2 && make
    - wget -O /tmp/proteinortho.tar.gz http://www.bioinf.uni-leipzig.de/Software/proteinortho/proteinortho_v5.16b.tar.gz && tar xzf proteinortho.tar.gz
    - mkdir /tmp/xa2multi; wget -O /tmp/xa2multi/xa2multi.pl https://raw.githubusercontent.com/lh3/bwa/master/xa2multi.pl && chmod +x /tmp/xa2multi/xa2multi.pl
    - wget -O /tmp/piranha-1.2.1.tar.gz http://smithlabresearch.org/downloads/piranha-1.2.1.tar.gz && cd /tmp/ && tar xzf piranha-1.2.1.tar.gz && cd piranha-1.2.1 && ./configure && make all
    - mkdir -p /tmp/perl5
    - export PERL_MB_OPT="--install_base /tmp/perl5"
    - export PERL_MM_OPT="INSTALL_BASE=/tmp/perl5"
    - export PERL5LIB=/tmp/mirdeep2/lib/perl5:/tmp/perl5/lib/:$PERL5LIB
    - git clone https://github.com/rajewsky-lab/mirdeep2.git /tmp/mirdeep2 && cd /tmp/mirdeep2 && perl install.pl && perl install.pl && mkdir -p /bin/indexes && chmod a+rwX bin/indexes
    - pip install --user --upgrade cutadapt
    - wget -O /tmp/gmap.tar.gz http://research-pub.gene.com/gmap/src/gmap-gsnap-2018-02-12.tar.gz && cd /tmp/ && tar xzf gmap.tar.gz && cd gmap-2018-02-12 && ./configure --with-simd-level=sse2 && make
    - wget -O /tmp/miRanda-aug2010.tar.gz http://cbio.mskcc.org/microrna_data/miRanda-aug2010.tar.gz && cd /tmp && tar xzf miRanda-aug2010.tar.gz && cd miRanda-3.3a && ./configure && make
    - mkdir -p /tmp/gffread && cd /tmp/gffread && git clone https://github.com/gpertea/gclib && cd gclib && git checkout b790ac157971c5e6da77d0c76ee9ebf26ec4a5ef && cd .. && git clone --branch v0.9.12 https://github.com/gpertea/gffread && cd gffread && make
    - cd $TRAVIS_BUILD_DIR
    - export PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine
    - git clone https://github.com/microPIECE-team/microPIECE-testset.git /tmp/microPIECE-testset
script:
    - travis_wait 60 t/run_travis.sh
after_success:
    - export PERL5OPT=""
    - cover -ignore_re=lib
    - cover -ignore_re=lib -report coveralls
