language: perl
sudo:
  required
addons:
  apt:
    packages:
      - cpanminus
services:
   - docker
before_install:
    - docker pull micropiece/micropiece
    - git clone https://github.com/microPIECE-team/microPIECE-testset.git /tmp/microPIECE-testset
    - git clone git://github.com/haarg/perl-travis-helper
    - source perl-travis-helper/init
    - build-perl
    - perl -V
install:
    - cpanm Devel::Cover Devel::Cover::Report::Coveralls 
script:
    - docker run --env PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine -it --rm -v $PWD:/opt/microPIECE -v /tmp/microPIECE-testset:/tmp/microPIECE-testset micropiece/micropiece /opt/microPIECE/t/run_travis.sh
after_success:
    - export PERL5OPT=""
    - cover -ignore_re=lib
    - cover -ignore_re=lib -report coveralls
